const plural = (n, one, many) => `${n} ${n === 1 ? one : many}`

export const STRINGS = {
  en: {
    materials: 'Materials',
    links: 'Links',
    evidence: 'Evidence',
    question: 'Question',
    answer: 'Answer',
    baseline: 'Baseline',
    lectern: 'Lectern',
    compare: 'Compare with baseline',
    language: 'Language',
    cost: 'Session cost',
    mock: 'mock answerer',
    priceUnknown: 'price unknown',
    addFile: 'Add file',
    sampleReadOnly: 'The sample lecture is read-only',
    startOver: 'Start over with new files?',
    home: 'Lectern: start over',
    sources: (n) => (n === 1 ? 'source' : 'sources'),
    viaLinks: 'reached through links',
    noLinks: 'no links: retrieval without link-following',
    notFound: 'Not found in the provided material',
    working: 'Finding evidence and checking each claim…',
    why: 'Why this evidence?',
    askPlaceholder: 'Ask about this lecture',
    send: 'Send question',
    intro: 'Ask a question. Each claim in the answer cites the speech, slides or notes it rests on.',
    evidenceEmpty: 'The evidence behind an answer appears here.',
    linked: 'linked',
    unsure: 'unsure',
    unlinked: 'not linked',
    confirm: 'Confirm',
    pairTitle: (p) =>
      `${p.a} · ${p.b}: ${p.links} cross-file links. Gate z ${p.z ?? '–'} (threshold ${p.threshold_z ?? '–'})` +
      `${p.setting === 'auto' ? '' : `, set to ${p.setting} by you`}. Click to mark ${p.links ? 'unrelated' : 'related'}.`,
    confirmTitle: 'Confirm these files belong together',
    otherPairs: 'Other file pairs',
    directMatch: 'direct match',
    via: (type) => `via ${type}`,
    missed: 'missed by baseline',
    baselineOnly: 'baseline only',
    audio: 'Audio',
    slide: 'Slide',
    figure: 'figure',
    notes: 'Notes',
    page: 'page',
    image: 'image',
    play: 'Play',
    pause: 'Pause',
    playRecording: 'Play the recording',
    pauseRecording: 'Pause the recording',
    playSegment: (range) => `Play ${range}`,
    timeline: 'Recording timeline',
    chip: (n, where) => `Evidence ${n}: ${where}`,
    meta: {
      slides: (n) => plural(n, 'slide', 'slides'),
      pages: (n) => plural(n, 'page', 'pages'),
      passages: (n) => plural(n, 'passage', 'passages'),
      skipped: 'not read',
    },
    linkType: { audio_slide: 'speech–slide', figure_text: 'figure–text', deictic: 'pointing', same_slide: 'same slide' },
    linkRow: { audio_slide: 'Speech ↔ slide', figure_text: 'Figure ↔ text', deictic: 'Pointing', same_slide: 'Same slide' },
    verdict: {
      supported: 'Supported by the evidence it cites',
      weak: 'Weak: cites no evidence',
      unsupported: 'Not supported by the evidence it cites',
      unchecked: 'Not checked',
    },
    counts: { supported: 'supported', weak: 'weak', unsupported: 'unsupported' },
    summary: (n, parts) => `${plural(n, 'claim', 'claims')} checked against the evidence they cite: ${parts}.`,
  },
  hi: {
    materials: 'सामग्री',
    links: 'लिंक',
    evidence: 'साक्ष्य',
    question: 'प्रश्न',
    answer: 'उत्तर',
    baseline: 'बेसलाइन',
    lectern: 'Lectern',
    compare: 'बेसलाइन से तुलना',
    language: 'भाषा',
    cost: 'सत्र की लागत',
    mock: 'मॉक उत्तरदाता',
    priceUnknown: 'कीमत अज्ञात',
    addFile: 'फ़ाइल जोड़ें',
    sampleReadOnly: 'नमूना व्याख्यान केवल पढ़ने के लिए है',
    startOver: 'नई फ़ाइलों के साथ फिर से शुरू करें?',
    home: 'Lectern: फिर से शुरू करें',
    sources: () => 'स्रोत',
    viaLinks: 'लिंक के ज़रिए मिले',
    noLinks: 'कोई लिंक नहीं: लिंक-अनुसरण के बिना खोज',
    notFound: 'दी गई सामग्री में नहीं मिला',
    working: 'साक्ष्य खोजा जा रहा है और हर दावे की जाँच हो रही है…',
    why: 'यह साक्ष्य क्यों?',
    askPlaceholder: 'इस व्याख्यान के बारे में पूछें',
    send: 'प्रश्न भेजें',
    intro: 'प्रश्न पूछें। उत्तर का हर दावा उस भाषण, स्लाइड या नोट्स का हवाला देता है जिस पर वह टिका है।',
    evidenceEmpty: 'उत्तर के पीछे का साक्ष्य यहाँ दिखेगा।',
    linked: 'जुड़ा',
    unsure: 'अनिश्चित',
    unlinked: 'नहीं जुड़ा',
    confirm: 'पुष्टि करें',
    pairTitle: (p) =>
      `${p.a} · ${p.b}: ${p.links} क्रॉस-फ़ाइल लिंक। गेट z ${p.z ?? '–'} (सीमा ${p.threshold_z ?? '–'})। ` +
      `बदलने के लिए क्लिक करें।`,
    confirmTitle: 'पुष्टि करें कि ये फ़ाइलें साथ हैं',
    otherPairs: 'अन्य फ़ाइल जोड़े',
    directMatch: 'सीधा मिलान',
    via: (type) => `${type} के ज़रिए`,
    missed: 'बेसलाइन से छूटा',
    baselineOnly: 'केवल बेसलाइन',
    audio: 'ऑडियो',
    slide: 'स्लाइड',
    figure: 'चित्र',
    notes: 'नोट्स',
    page: 'पृष्ठ',
    image: 'छवि',
    play: 'चलाएँ',
    pause: 'रोकें',
    playRecording: 'रिकॉर्डिंग चलाएँ',
    pauseRecording: 'रिकॉर्डिंग रोकें',
    playSegment: (range) => `${range} चलाएँ`,
    timeline: 'रिकॉर्डिंग की समयरेखा',
    chip: (n, where) => `साक्ष्य ${n}: ${where}`,
    meta: {
      slides: (n) => `${n} स्लाइड`,
      pages: (n) => `${n} पृष्ठ`,
      passages: (n) => `${n} अंश`,
      skipped: 'पढ़ा नहीं गया',
    },
    linkType: { audio_slide: 'भाषण–स्लाइड', figure_text: 'चित्र–पाठ', deictic: 'संकेत', same_slide: 'एक ही स्लाइड' },
    linkRow: { audio_slide: 'भाषण ↔ स्लाइड', figure_text: 'चित्र ↔ पाठ', deictic: 'संकेत', same_slide: 'एक ही स्लाइड' },
    verdict: {
      supported: 'उद्धृत साक्ष्य से समर्थित',
      weak: 'कमज़ोर: कोई साक्ष्य उद्धृत नहीं',
      unsupported: 'उद्धृत साक्ष्य से समर्थित नहीं',
      unchecked: 'जाँचा नहीं गया',
    },
    counts: { supported: 'समर्थित', weak: 'कमज़ोर', unsupported: 'असमर्थित' },
    summary: (n, parts) => `${n} दावों की जाँच उनके उद्धृत साक्ष्य से की गई: ${parts}।`,
  },
}

/** Where a unit sits, as plain text (labels for assistive tech): "Audio · 18:40–19:05". */
export function placeText(unit, t, clock) {
  const loc = unit.location || {}
  if (unit.modality === 'speech') return `${t.audio} · ${clock(loc.start_s)}–${clock(loc.end_s)}`
  if (unit.modality === 'slides') return `${t.slide} ${loc.page ?? ''}${unit.figure ? ` · ${t.figure}` : ''}`
  if (loc.page != null) return `${t.notes} · ${t.page} ${loc.page}`
  return `${t.notes} · ${unit.figure ? t.image : unit.file}`
}
