const plural = (n, one, many) => `${n} ${n === 1 ? one : many}`

export const STRINGS = {
  en: {
    dropLabel: 'Add lecture files: drop them here, or press Enter to choose them',
    dropTitle: 'Drop lecture files here',
    dropHint: 'or click to choose them',
    kinds: { speech: 'Speech', slides: 'Slides', notes: 'Notes' },
    kindHints: { speech: 'the recording', slides: 'the deck', notes: 'papers, handouts, scans' },
    trySample: 'Try the sample lecture',
    loadingSample: 'Loading the sample lecture',
    building: 'Building the lecture',
    stages: {
      ingest: 'Read the files',
      index: 'Index the evidence',
      link: 'Link speech, slides and notes',
      pairs: 'Check which files belong together',
    },
    transcribing: 'Speech is transcribed on this machine; this is the slow step.',
    queued: 'Waiting for another lecture to finish; they share the CPU…',
    startAgain: 'Start again',
    close: 'Close',
    whyIntro: (n, direct, via) =>
      `${plural(n, 'piece', 'pieces')} of evidence: ${direct} matched the question directly, ${via} ${via === 1 ? 'was' : 'were'} reached by following links from them.`,
    graphLabel: (nodes, edges) => `Graph of ${plural(nodes, 'unit', 'units')} and ${plural(edges, 'link', 'links')}`,
    linksBetween: 'Links among this evidence',
    noEdges: 'None of these units are linked to each other.',
    seedOnly: 'seed',
    checking: 'checking',
    materials: 'Materials',
    links: 'Links',
    evidence: 'Evidence',
    question: 'Question',
    answer: 'Answer',
    baseline: 'Baseline',
    lectern: 'Lectern',
    compare: 'Compare with baseline',
    language: 'Language',
    cost: 'Session cost',
    mock: 'mock answerer',
    priceUnknown: 'price unknown',
    addFile: 'Add file',
    sampleReadOnly: 'The sample lecture is read-only',
    startOver: 'Start over with new files?',
    home: 'Lectern: start over',
    sources: (n) => (n === 1 ? 'source' : 'sources'),
    viaLinks: 'reached through links',
    noLinks: 'no links: retrieval without link-following',
    notFound: 'Not found in the provided material',
    working: 'Finding evidence and checking each claim…',
    why: 'Why this evidence?',
    askPlaceholder: 'Ask about this lecture',
    send: 'Send question',
    intro: 'Ask a question. Each claim in the answer cites the speech, slides or notes it rests on.',
    evidenceEmpty: 'The evidence behind an answer appears here.',
    linked: 'linked',
    unsure: 'unsure',
    unlinked: 'not linked',
    confirm: 'Confirm',
    pairTitle: (p) =>
      `${p.a} · ${p.b}: ${p.links} cross-file links. Gate z ${p.z ?? '–'} (threshold ${p.threshold_z ?? '–'})` +
      `${p.setting === 'auto' ? '' : `, set to ${p.setting} by you`}. Click to mark ${p.links ? 'unrelated' : 'related'}.`,
    confirmTitle: 'Confirm these files belong together',
    otherPairs: 'Other file pairs',
    directMatch: 'direct match',
    via: (type) => `via ${type}`,
    notRetrieved: 'not retrieved by baseline',
    linkedTitle: 'Linked to this evidence',
    linkedFrom: (where) => `linked from ${where}`,
    addPaper: 'add the paper',
    baselineOnly: 'baseline only',
    audio: 'Audio',
    slide: 'Slide',
    figure: 'figure',
    notes: 'Notes',
    page: 'page',
    image: 'image',
    playRecording: 'Play the recording',
    pauseRecording: 'Pause the recording',
    playSegment: (range) => `Play ${range}`,
    timeline: 'Recording timeline',
    chip: (n, where) => `Evidence ${n}: ${where}`,
    meta: {
      slides: (n) => plural(n, 'slide', 'slides'),
      pages: (n) => plural(n, 'page', 'pages'),
      passages: (n) => plural(n, 'passage', 'passages'),
    },
    linkType: { audio_slide: 'speech–slide', figure_text: 'figure–text', deictic: 'pointing', same_slide: 'same slide' },
    linkRow: { audio_slide: 'Speech ↔ slide', figure_text: 'Figure ↔ text', deictic: 'Pointing', same_slide: 'Same slide' },
    verdict: {
      supported: 'Supported by the evidence it cites',
      weak: 'Weak: cites no evidence',
      unsupported: 'Not supported by the evidence it cites',
      unchecked: 'Not checked',
    },
    counts: { supported: 'supported', weak: 'weak', unsupported: 'unsupported' },
    summary: (n, parts) => `${plural(n, 'claim', 'claims')} checked against the evidence they cite: ${parts}.`,
  },
  hi: {
    dropLabel: 'व्याख्यान फ़ाइलें जोड़ें: यहाँ छोड़ें, या चुनने के लिए Enter दबाएँ',
    dropTitle: 'व्याख्यान की फ़ाइलें यहाँ छोड़ें',
    dropHint: 'या चुनने के लिए क्लिक करें',
    kinds: { speech: 'भाषण', slides: 'स्लाइड', notes: 'नोट्स' },
    kindHints: { speech: 'रिकॉर्डिंग', slides: 'स्लाइड डेक', notes: 'पेपर, हैंडआउट, स्कैन' },
    trySample: 'नमूना व्याख्यान आज़माएँ',
    loadingSample: 'नमूना व्याख्यान लोड हो रहा है',
    building: 'व्याख्यान तैयार हो रहा है',
    stages: {
      ingest: 'फ़ाइलें पढ़ना',
      index: 'साक्ष्य का इंडेक्स बनाना',
      link: 'भाषण, स्लाइड और नोट्स को जोड़ना',
      pairs: 'जाँचना कि कौन-सी फ़ाइलें साथ हैं',
    },
    transcribing: 'भाषण का ट्रांसक्रिप्शन इसी मशीन पर होता है; यही धीमा चरण है।',
    queued: 'दूसरे व्याख्यान के पूरा होने की प्रतीक्षा; दोनों एक ही CPU साझा करते हैं…',
    startAgain: 'फिर से शुरू करें',
    close: 'बंद करें',
    whyIntro: (n, direct, via) => `साक्ष्य के ${n} अंश: ${direct} सीधे प्रश्न से मिले, ${via} उनसे लिंक के ज़रिए पहुँचे।`,
    graphLabel: (nodes, edges) => `${nodes} इकाइयों और ${edges} लिंक का ग्राफ़`,
    linksBetween: 'इस साक्ष्य के बीच लिंक',
    noEdges: 'इनमें से कोई इकाई आपस में जुड़ी नहीं है।',
    seedOnly: 'बीज',
    checking: 'जाँच जारी',
    materials: 'सामग्री',
    links: 'लिंक',
    evidence: 'साक्ष्य',
    question: 'प्रश्न',
    answer: 'उत्तर',
    baseline: 'बेसलाइन',
    lectern: 'Lectern',
    compare: 'बेसलाइन से तुलना',
    language: 'भाषा',
    cost: 'सत्र की लागत',
    mock: 'मॉक उत्तरदाता',
    priceUnknown: 'कीमत अज्ञात',
    addFile: 'फ़ाइल जोड़ें',
    sampleReadOnly: 'नमूना व्याख्यान केवल पढ़ने के लिए है',
    startOver: 'नई फ़ाइलों के साथ फिर से शुरू करें?',
    home: 'Lectern: फिर से शुरू करें',
    sources: () => 'स्रोत',
    viaLinks: 'लिंक के ज़रिए मिले',
    noLinks: 'कोई लिंक नहीं: लिंक-अनुसरण के बिना खोज',
    notFound: 'दी गई सामग्री में नहीं मिला',
    working: 'साक्ष्य खोजा जा रहा है और हर दावे की जाँच हो रही है…',
    why: 'यह साक्ष्य क्यों?',
    askPlaceholder: 'इस व्याख्यान के बारे में पूछें',
    send: 'प्रश्न भेजें',
    intro: 'प्रश्न पूछें। उत्तर का हर दावा उस भाषण, स्लाइड या नोट्स का हवाला देता है जिस पर वह टिका है।',
    evidenceEmpty: 'उत्तर के पीछे का साक्ष्य यहाँ दिखेगा।',
    linked: 'जुड़ा',
    unsure: 'अनिश्चित',
    unlinked: 'नहीं जुड़ा',
    confirm: 'पुष्टि करें',
    pairTitle: (p) =>
      `${p.a} · ${p.b}: ${p.links} क्रॉस-फ़ाइल लिंक। गेट z ${p.z ?? '–'} (सीमा ${p.threshold_z ?? '–'})। ` +
      `बदलने के लिए क्लिक करें।`,
    confirmTitle: 'पुष्टि करें कि ये फ़ाइलें साथ हैं',
    otherPairs: 'अन्य फ़ाइल जोड़े',
    directMatch: 'सीधा मिलान',
    via: (type) => `${type} के ज़रिए`,
    notRetrieved: 'बेसलाइन द्वारा प्राप्त नहीं',
    linkedTitle: 'इस साक्ष्य से जुड़ा',
    linkedFrom: (where) => `${where} से जुड़ा`,
    addPaper: 'पेपर भी जोड़ें',
    baselineOnly: 'केवल बेसलाइन',
    audio: 'ऑडियो',
    slide: 'स्लाइड',
    figure: 'चित्र',
    notes: 'नोट्स',
    page: 'पृष्ठ',
    image: 'छवि',
    playRecording: 'रिकॉर्डिंग चलाएँ',
    pauseRecording: 'रिकॉर्डिंग रोकें',
    playSegment: (range) => `${range} चलाएँ`,
    timeline: 'रिकॉर्डिंग की समयरेखा',
    chip: (n, where) => `साक्ष्य ${n}: ${where}`,
    meta: {
      slides: (n) => `${n} स्लाइड`,
      pages: (n) => `${n} पृष्ठ`,
      passages: (n) => `${n} अंश`,
    },
    linkType: { audio_slide: 'भाषण–स्लाइड', figure_text: 'चित्र–पाठ', deictic: 'संकेत', same_slide: 'एक ही स्लाइड' },
    linkRow: { audio_slide: 'भाषण ↔ स्लाइड', figure_text: 'चित्र ↔ पाठ', deictic: 'संकेत', same_slide: 'एक ही स्लाइड' },
    verdict: {
      supported: 'उद्धृत साक्ष्य से समर्थित',
      weak: 'कमज़ोर: कोई साक्ष्य उद्धृत नहीं',
      unsupported: 'उद्धृत साक्ष्य से समर्थित नहीं',
      unchecked: 'जाँचा नहीं गया',
    },
    counts: { supported: 'समर्थित', weak: 'कमज़ोर', unsupported: 'असमर्थित' },
    summary: (n, parts) => `${n} दावों की जाँच उनके उद्धृत साक्ष्य से की गई: ${parts}।`,
  },
}

/** Where a unit sits, as plain text (labels for assistive tech): "Audio · 18:40–19:05". */
export function placeText(unit, t, clock) {
  const loc = unit.location || {}
  if (unit.modality === 'speech') return `${t.audio} · ${clock(loc.start_s)}–${clock(loc.end_s)}`
  if (unit.modality === 'slides') return `${t.slide} ${loc.page ?? ''}${unit.figure ? ` · ${t.figure}` : ''}`
  if (loc.page != null) return `${t.notes} · ${t.page} ${loc.page}`
  return `${t.notes} · ${unit.figure ? t.image : unit.file}`
}
